# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab3e274448b5517438eef1268c5c183e884947a125976e9b6482b2fb76c49edf5a8a99f5027caccea8985b8251826860b913cb92766d0619f1e9427abc7852c4

test:
  secret_key_base: 07786c8f2c277fc83967ef9568d1bb14d741ad2c9bbb7cc64eaeea4a24ffee0f56e2fb540b3b70f5cd5335549aeb300745b096742ed26206f10a7512a74b86fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
